/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inchok_aria2_Aria2 */

#ifndef _Included_com_inchok_aria2_Aria2
#define _Included_com_inchok_aria2_Aria2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_inchok_aria2_Aria2_RESPONSE_OK
#define com_inchok_aria2_Aria2_RESPONSE_OK 0L
/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    initializeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    deInitializeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_deInitializeNative
  (JNIEnv *, jclass);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    newSessionNative
 * Signature: (JLcom/inchok/aria2/SessionConfig;)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_newSessionNative
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    finalSessionNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_finalSessionNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    hexToGidNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_hexToGidNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    gidToHexNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_gidToHexNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    isNullNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_inchok_aria2_Aria2_isNullNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getGidNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getGidNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    setGidNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_inchok_aria2_Aria2_setGidNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    newGidNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_newGidNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    newKeyValuesNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_newKeyValuesNative
  (JNIEnv *, jclass);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    setKeyValuesNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_inchok_aria2_Aria2_setKeyValuesNative
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getKeyValuesNative
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_getKeyValuesNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getStatusNative
 * Signature: (J)Lcom/inchok/aria2/DownloadStatus;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getStatusNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getTotalLengthNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getTotalLengthNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getCompletedLengthNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getCompletedLengthNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getUploadedLengthNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getUploadedLengthNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getBitFieldNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_getBitFieldNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getDownloadSpeedNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_getDownloadSpeedNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getUploadSpeedNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_getUploadSpeedNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getInfoHashNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_getInfoHashNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getPieceLengthNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getPieceLengthNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getPieceCountNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_getPieceCountNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getConnectionCountNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_getConnectionCountNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getErrorCodeNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_getErrorCodeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getFollowedByNative
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getFollowedByNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getFollowingNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getFollowingNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getBelongsToNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getBelongsToNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getDirNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_getDirNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getFilesDataNative
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getFilesDataNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getFileCountNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_getFileCountNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getFileNative
 * Signature: (JI)Lcom/inchok/aria2/FileData;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getFileNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getBtMetaInfoNative
 * Signature: (J)Lcom/inchok/aria2/BtMetaInfoData;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getBtMetaInfoNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getOptionNative
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_getOptionNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getOptionsNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getOptionsNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    deleteDownloadHandleNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_inchok_aria2_Aria2_deleteDownloadHandleNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    runNative
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_runNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    addUriNative
 * Signature: (JJLjava/util/List;JI)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_addUriNative
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    addMetaLinkNative
 * Signature: (JLjava/util/List;Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_addMetaLinkNative
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    addTorrentNative
 * Signature: (JJLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_addTorrentNative__JJLjava_lang_String_2JI
  (JNIEnv *, jclass, jlong, jlong, jstring, jlong, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    addTorrentNative
 * Signature: (JJLjava/lang/String;Ljava/util/List;JI)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_addTorrentNative__JJLjava_lang_String_2Ljava_util_List_2JI
  (JNIEnv *, jclass, jlong, jlong, jstring, jobject, jlong, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getActiveDownloadNative
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getActiveDownloadNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    removeDownloadNative
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_removeDownloadNative
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    pauseDownloadNative
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_pauseDownloadNative
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    unpauseDownloadNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_unpauseDownloadNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    changeOptionNative
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_changeOptionNative
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getGlobalOptionNative
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_inchok_aria2_Aria2_getGlobalOptionNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getGlobalOptionsNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getGlobalOptionsNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    changeGlobalOptionNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_changeGlobalOptionNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getGlobalStatNative
 * Signature: (J)Lcom/inchok/aria2/GlobalStat;
 */
JNIEXPORT jobject JNICALL Java_com_inchok_aria2_Aria2_getGlobalStatNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    changePositionNative
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_changePositionNative
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    shutdownNative
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_inchok_aria2_Aria2_shutdownNative
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_inchok_aria2_Aria2
 * Method:    getDownloadHandleNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_inchok_aria2_Aria2_getDownloadHandleNative
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
